export const PORTFOLIO_CATEGORIES = [
  { id: 'featured', label: '🌟 Featured Showcase', count: 18 },
  { id: 'political', label: '🏛️ Political & Yatras', count: 29 },
  { id: 'food', label: '🍔 Food & Dining', count: 17 },
  { id: 'retail', label: '🛍️ Retail & Brands', count: 19 },
  { id: 'hospitality', label: '🏨 Luxury Hospitality', count: 10 },
  { id: 'aviation', label: '✈️ Aviation & Mobility', count: 11 },
  { id: 'education', label: '🎓 Education & Institutes', count: 11 },
  { id: 'salon', label: '💇 Salons & Grooming', count: 4 },
  { id: 'all', label: '⚡ All Work', count: 101 },
]

export const TOP_CLIENT_NAMES = [
  'Tejashwi Yadav',
  'Zepto',
  'Blinkit',
  'Pappu Yadav (MP)',
  'MakeMyTrip',
  'Akasa Air',
  'Pawan Singh',
  "Domino's",
  'KFC',
  'Khesari Lal Yadav',
  'City Centre Mall',
  'Croma',
  'Lacoste',
  'FirstCry',
  'Sudha Milk',
  'Sambhavi Choudhary (MP)',
  'The Taj Studio',
  'La Cabana Goa',
  'Mentors Eduserv',
  'GD Goenka',
  'Aditya Vision',
  'iDestiny Apple Reseller',
  'Jan Vishwas Yatra',
  'Voter Adhikar Yatra',
  'Biryani Blues',
  'Pind Balluchi',
  'Sita Ram Diwan Chand',
  'Looks Salon',
  'ISKCON Patna',
]

export const EXTENDED_PORTFOLIO = [
  // ═══════════════════════════════════════════════════════
  // 🏛️ POLITICAL LEADERS & STATEWIDE CAMPAIGNS (29 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'pol-1',
    name: 'Tejashwi Yadav',
    category: 'political',
    categoryName: 'Political & Public Strategy',
    role: 'Mass Digital Strategy, Youth Outreach & Campaign Narrative',
    location: 'Bihar',
    badge: 'Former Deputy CM',
    impact: '25M+ Digital Impressions',
    img: 'https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=700&q=80',
    tags: ['Public Strategy', 'Social Narrative', 'Live Broadcasts'],
    featured: true,
  },
  {
    id: 'pol-2',
    name: 'Jan Vishwas Yatra (RJD)',
    category: 'political',
    categoryName: 'Mass Political Movement',
    role: 'Statewide Digital Coverage, Drone Feeds & Viral Reel Engines',
    location: 'All 38 Districts, Bihar',
    badge: 'Mega Statewide Yatra',
    impact: '15M+ Video Views across Bihar',
    img: 'https://images.unsplash.com/photo-1596769408479-7a561110023a?w=700&q=80',
    tags: ['Ground Media', 'Viral Reels', 'Route Promotion'],
    featured: true,
  },
  {
    id: 'pol-3',
    name: 'Rajesh Ranjan (Pappu Yadav)',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'High-Impact Ground Narrative, Social Media Dominance & Grassroots Connect',
    location: 'Purnea, Bihar',
    badge: 'Member of Parliament (MP)',
    impact: 'Historic Electoral Victory',
    img: 'https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=700&q=80',
    tags: ['Lok Sabha Campaign', 'Crisis PR', 'Voter Connect'],
    featured: true,
  },
  {
    id: 'pol-4',
    name: 'Pawan Singh',
    category: 'political',
    categoryName: 'Celebrity Campaign & Political Brand',
    role: 'Star Persona Digital Management, Rally Broadcasts & Fan Mobilization',
    location: 'Bihar & National',
    badge: 'Cultural Icon & Politician',
    impact: '40M+ Multi-Platform Reach',
    img: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=700&q=80',
    tags: ['Star PR', 'Rally Campaigns', 'YouTube Engine'],
    featured: true,
  },
  {
    id: 'pol-5',
    name: 'Khesari Lal Yadav',
    category: 'political',
    categoryName: 'Celebrity & Cultural Outreach',
    role: 'Mass Audience Digital Management, Musical Release Promotions & Crowd Campaigns',
    location: 'Pan-India',
    badge: 'Megastar & Youth Icon',
    impact: '50M+ Engagements',
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=700&q=80',
    tags: ['Youth Outreach', 'Digital Presence', 'Content Strategy'],
    featured: true,
  },
  {
    id: 'pol-6',
    name: 'Sambhavi Choudhary',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'Modern Youth Campaigning, Women Empowerment Narrative & Social Media',
    location: 'Samastipur, Bihar',
    badge: 'MP (LJPR) - Youngest MP',
    impact: 'Top-Trending Youth Campaign',
    img: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=700&q=80',
    tags: ['Electoral Media', 'Youth Outreach', 'Voter Ads'],
    featured: true,
  },
  {
    id: 'pol-7',
    name: 'Misa Bharti',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'Parliamentary Constituency Digital Outreach, Women Voters Mobilization',
    location: 'Patliputra, Bihar',
    badge: 'Member of Parliament (MP)',
    impact: 'Overwhelming Constituency Reach',
    img: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=700&q=80',
    tags: ['Parliamentary PR', 'Booth Level Ads', 'Speech Clips'],
  },
  {
    id: 'pol-8',
    name: 'Voter Adhikar Yatra (Congress)',
    category: 'political',
    categoryName: 'Mass Democratic Movement',
    role: 'Multi-District Yatra Media Coverage, Press Management & Live Feeds',
    location: 'Aurangabad, Rohtas & Bhagalpur',
    badge: 'Tri-District Yatra',
    impact: '100+ Live Broadcast Feeds',
    img: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=700&q=80',
    tags: ['Yatra Media', 'Press Releases', 'Ground Volunteers'],
    featured: true,
  },
  {
    id: 'pol-9',
    name: 'Tej Pratap Yadav',
    category: 'political',
    categoryName: 'Public Leadership & Youth Mobilization',
    role: 'High-Impact Social Campaigns, Mass Rally Creatives & Dynamic Branding',
    location: 'Hasanpur, Bihar',
    badge: 'Former Cabinet Minister',
    impact: '10M+ Video Engagements',
    img: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=700&q=80',
    tags: ['Social Branding', 'Youth Rallies', 'Reel Campaigns'],
  },
  {
    id: 'pol-10',
    name: 'Rohini Acharya',
    category: 'political',
    categoryName: 'Electoral Campaign & Social Influence',
    role: 'Empathetic Public Narrative, Digital Media Production & Targeted Campaigns',
    location: 'Saran, Bihar',
    badge: 'Prominent Public Leader',
    impact: '8M+ Social Shares & Views',
    img: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=700&q=80',
    tags: ['Constituency Outreach', 'Narrative PR', 'Social Media'],
  },
  {
    id: 'pol-11',
    name: 'Sudhakar Singh',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'Farmers Rights Campaigning, Parliamentary PR & Regional Dominance',
    location: 'Buxar, Bihar',
    badge: 'Member of Parliament (MP)',
    impact: 'Decisive Electoral Victory',
    img: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=700&q=80',
    tags: ['Agrarian Outreach', 'Constituency Ads', 'Speeches'],
  },
  {
    id: 'pol-12',
    name: 'Rajesh Verma',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'Modern Youth Campaign, Micro-Targeted Booth Ads & Dynamic Creatives',
    location: 'Khagaria / Araria, Bihar',
    badge: 'Member of Parliament (MP - LJPR)',
    impact: 'High-Margin Parliamentary Win',
    img: 'https://images.unsplash.com/photo-1556157382-97eda2d62296?w=700&q=80',
    tags: ['Data Targeting', 'Constituency PR', 'Video Ads'],
  },
  {
    id: 'pol-13',
    name: 'Dilip Jaiswal',
    category: 'political',
    categoryName: 'Party State Leadership & Policy PR',
    role: 'Organizational Communication, Press Conferences & State Digital Outreach',
    location: 'Bihar',
    badge: 'State President BJP & Minister',
    impact: 'Statewide Media Distribution',
    img: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=700&q=80',
    tags: ['Leadership PR', 'Press Outreach', 'Party Campaigns'],
  },
  {
    id: 'pol-14',
    name: 'Ram Kripal Yadav',
    category: 'political',
    categoryName: 'Constituency PR & Mass Reach',
    role: 'Grassroots Voter Engagement, Development Narrative & Social Profiles',
    location: 'Patliputra, Bihar',
    badge: 'Former Union Minister & Senior MLA',
    impact: '500K+ Constituency Voters Reached',
    img: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=700&q=80',
    tags: ['Grassroots Media', 'Constituency Reports', 'Audio-Visual'],
  },
  {
    id: 'pol-15',
    name: 'Alok Mehta',
    category: 'political',
    categoryName: 'Public Policy & Constituency PR',
    role: 'Departmental Accomplishment Showcases, Video Production & Press Feeds',
    location: 'Ujiarpur, Bihar',
    badge: 'Former Cabinet Minister',
    impact: '3M+ Targeted Constituency Impressions',
    img: 'https://images.unsplash.com/photo-1551836022-deb4988cc6c0?w=700&q=80',
    tags: ['Policy Campaigns', 'Constituency Connect', 'Video PR'],
  },
  {
    id: 'pol-16',
    name: 'Neeraj Kumar',
    category: 'political',
    categoryName: 'Spokesperson PR & Media Debate Strategy',
    role: 'Press Fact-Sheets, Quick-Response Digital Cards & Debate Counter-Points',
    location: 'Bihar',
    badge: 'Chief Spokesperson & MLC (JDU)',
    impact: 'Top-Quoted Newsbite Engine',
    img: 'https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=700&q=80',
    tags: ['Media Counter-PR', 'Press Cards', 'Fact Sheets'],
  },
  {
    id: 'pol-17',
    name: 'Sanjeev Chaurasia',
    category: 'political',
    categoryName: 'Urban Legislative Campaign',
    role: 'Urban Voter Micro-Targeting, Resident Welfare Outreach & City Creatives',
    location: 'Digha, Patna',
    badge: 'Senior MLA (BJP)',
    impact: '70% Urban Voter Digital Coverage',
    img: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=700&q=80',
    tags: ['Urban Campaigns', 'WhatsApp Groups', 'Local Issues'],
  },
  {
    id: 'pol-18',
    name: 'Siddharth Saurav',
    category: 'political',
    categoryName: 'Vidhan Sabha Electoral Campaign',
    role: 'Rural & Semi-Urban Outreach, Ground Feedback Gathering & Video Rallies',
    location: 'Bikram Vidhan Sabha',
    badge: 'Sitting MLA',
    impact: '2.5M+ Rural Video Views',
    img: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&q=80',
    tags: ['Rural Media', 'Constituency Ads', 'Rally Reels'],
  },
  {
    id: 'pol-19',
    name: 'Sandeep Saurav',
    category: 'political',
    categoryName: 'Youth & Employment Movement Strategy',
    role: 'Teacher & Student Rights Digital Narrative, Intellectual Discourse & Rallies',
    location: 'Paliganj Vidhan Sabha',
    badge: 'Sitting MLA (CPI-ML)',
    impact: 'Massive Student & Youth Engagement',
    img: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=700&q=80',
    tags: ['Youth Rights', 'Education Campaigns', 'Video Interviews'],
  },
  {
    id: 'pol-20',
    name: 'Sanjay Singh',
    category: 'political',
    categoryName: 'Constituency Growth Narrative',
    role: 'Development Milestone Campaigns, Community Video Documentaries',
    location: 'Mahua, Bihar',
    badge: 'MLA & Former Minister',
    impact: '1.8M+ Localized Engagements',
    img: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=700&q=80',
    tags: ['Development PR', 'Local Campaigns', 'Community Connect'],
  },
  {
    id: 'pol-21',
    name: 'Neeraj Kumar Bablu',
    category: 'political',
    categoryName: 'Constituency Mobilization',
    role: 'Kosi Region Mass Outreach, Local Development Showcases & Facebook Ads',
    location: 'Chhatapur, Bihar',
    badge: 'Former Minister & Senior MLA',
    impact: '400K+ Regional Voters Reached',
    img: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=700&q=80',
    tags: ['Regional Growth', 'Facebook Ads', 'Audio Campaigns'],
  },
  {
    id: 'pol-22',
    name: 'Vinod Narayan Jha',
    category: 'political',
    categoryName: 'Mithila Region Senior Leadership PR',
    role: 'Cultural & Infrastructural Narrative, Press Media & Constituency Cards',
    location: 'Madhubani / Benipatti',
    badge: 'Former Cabinet Minister',
    impact: 'High-Trust Senior Statesman Image',
    img: 'https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=700&q=80',
    tags: ['Mithila Heritage', 'Policy Communication', 'Press Columns'],
  },
  {
    id: 'pol-23',
    name: 'Pawan Jaiswal',
    category: 'political',
    categoryName: 'Vidhan Sabha Electoral Campaign',
    role: 'Ground Mobilization, Youth Cricket & Cultural Event Integrations',
    location: 'Dhaka Vidhan Sabha, Champaran',
    badge: 'Sitting MLA',
    impact: '1.2M+ Champaran Outreach',
    img: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=700&q=80',
    tags: ['Constituency Events', 'Digital Posters', 'Speeches'],
  },
  {
    id: 'pol-24',
    name: 'Rajesh Gupta',
    category: 'political',
    categoryName: 'Urban Commercial & Community PR',
    role: 'Trader Community Outreach, GST & Local Business Forums Digital Support',
    location: 'Patna City',
    badge: 'Former MLA',
    impact: 'Complete Merchant Community Coverage',
    img: 'https://images.unsplash.com/photo-1444653614773-995cb1ef902f?w=700&q=80',
    tags: ['Merchant Connect', 'Community Forums', 'Local Issues'],
  },
  {
    id: 'pol-25',
    name: 'Anita Devi (w/o Ashok Mahto)',
    category: 'political',
    categoryName: 'Lok Sabha Electoral Campaign',
    role: 'Subaltern Empowerment Narrative, High-Engagement Video Campaigns',
    location: 'Warsaliganj / Nawada',
    badge: 'Lok Sabha Candidate',
    impact: 'Viral Rural Grassroots Campaign',
    img: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=700&q=80',
    tags: ['Grassroots Video', 'Empowerment Theme', 'Rally Ads'],
  },
  {
    id: 'pol-26',
    name: 'Vishal Prashant',
    category: 'political',
    categoryName: 'Vidhan Sabha Youth Campaign',
    role: 'Fresh Face Electoral Strategy, Dynamic Reel Series & Booth Outreach',
    location: 'Tekari Vidhan Sabha, Gaya',
    badge: 'Vidhan Sabha Leader',
    impact: '750K+ Local Video Views',
    img: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=700&q=80',
    tags: ['Youth Leadership', 'Reel Series', 'Ground Connect'],
  },
  {
    id: 'pol-27',
    name: 'Shivani Shukla',
    category: 'political',
    categoryName: 'Women in Politics Movement',
    role: 'Women Leadership Positioning, Educational Reforms Agenda & Campaign Media',
    location: 'Lalganj Vidhan Sabha',
    badge: 'Prominent Vidhan Sabha Leader',
    impact: '500K+ Women Voters Reached',
    img: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=700&q=80',
    tags: ['Women Leadership', 'Education Agendas', 'Constituency PR'],
  },
  {
    id: 'pol-28',
    name: 'Malay Rava Roy',
    category: 'political',
    categoryName: 'North Bengal Assembly Campaign',
    role: 'Bilingual Social Campaigning (Bengali/Hindi), Border Community Outreach',
    location: 'Tufanganj, West Bengal',
    badge: 'West Bengal Assembly Leader',
    impact: 'Cross-Border Electoral Footprint',
    img: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=700&q=80',
    tags: ['Bengal Campaigns', 'Vernacular Media', 'Constituency Ads'],
  },
  {
    id: 'pol-29',
    name: 'Sumita Sinha',
    category: 'political',
    categoryName: 'Coastal Bengal Assembly Campaign',
    role: 'Fisheries & Agricultural Economic Campaign, Local Grassroots Outreach',
    location: 'Kanthi Uttar, West Bengal',
    badge: 'West Bengal Assembly Leader',
    impact: '800K+ Rural Bengal Reach',
    img: 'https://images.unsplash.com/photo-1573497019236-17f8177b81e8?w=700&q=80',
    tags: ['Vernacular Campaigns', 'Rural Mobilization', 'Constituency PR'],
  },

  // ═══════════════════════════════════════════════════════
  // 🍔 FOOD, DINING & QSR CHAINS (17 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'food-1',
    name: "Domino's Pizza",
    category: 'food',
    categoryName: 'National QSR Brand',
    role: 'Hyperlocal Store Promotions, App Download Ads & Weekend Sales Drives',
    location: 'Multiple Cities, India',
    badge: 'Global Pizza Giant',
    impact: '4.5x Weekend App Orders',
    img: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=700&q=80',
    tags: ['App Installs', 'Meta Performance Ads', 'Delivery Surge'],
    featured: true,
  },
  {
    id: 'food-2',
    name: 'KFC India',
    category: 'food',
    categoryName: 'Global Fried Chicken Giant',
    role: 'Outlet Footfall Campaigns, Festive Bucket Offers & Reel Creative Production',
    location: 'National Outlets',
    badge: 'Global QSR Giant',
    impact: '3.8x Local Dine-In Traffic',
    img: 'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?w=700&q=80',
    tags: ['Footfall Campaigns', 'Reels Production', 'Festive Offers'],
    featured: true,
  },
  {
    id: 'food-3',
    name: 'Biryani Blues',
    category: 'food',
    categoryName: 'Leading Biryani Chain',
    role: 'Late-Night Cravings Performance Campaigns, Handi Biryani Reel Campaigns',
    location: 'Delhi NCR',
    badge: 'Premier North India Brand',
    impact: '120K+ Monthly Orders Driven',
    img: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=700&q=80',
    tags: ['Swiggy/Zomato Ads', 'Night Hunger Ads', 'Food Video'],
    featured: true,
  },
  {
    id: 'food-4',
    name: 'Sita Ram Diwan Chand',
    category: 'food',
    categoryName: 'Legendary Indian Heritage Food',
    role: 'Pan-India Cult Branding, Food Influencer Collabs & Heritage Storytelling',
    location: 'Paharganj, Delhi',
    badge: "India's Most Famous Chole Bhature",
    impact: '20M+ Organic Views across India',
    img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80',
    tags: ['Food Influencers', 'Heritage PR', 'Tourists Magnet'],
    featured: true,
  },
  {
    id: 'food-5',
    name: 'Pind Balluchi',
    category: 'food',
    categoryName: 'Heritage North Indian Dining',
    role: 'Family Dining Footfall Drives, Village Theme Ambience Creatives & Banquet Bookings',
    location: 'Delhi NCR & Pan-India',
    badge: 'Iconic Dine-In Chain',
    impact: '85% Weekend Table Occupancy',
    img: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&q=80',
    tags: ['Dine-In Footfall', 'Banquet Leads', 'Heritage Theme'],
    featured: true,
  },
  {
    id: 'food-6',
    name: 'Sandoz',
    category: 'food',
    categoryName: 'Legendary Mughlai & North Indian Chain',
    role: 'Butter Chicken Signature Push, Multi-Outlet Local Geo-Fencing Campaigns',
    location: 'Delhi & Punjab',
    badge: 'Famous Regional Brand',
    impact: '3.4x Dine-In & Delivery Volume',
    img: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700&q=80',
    tags: ['Geo-Targeted Ads', 'Influencer Tastings', 'Brand Refresh'],
  },
  {
    id: 'food-7',
    name: 'Hari Lal Sweets & Restaurant',
    category: 'food',
    categoryName: 'Patna Premier Sweets & Dining',
    role: 'Diwali & Wedding Mithai Campaigns, Multi-Store Hyperlocal Google & Meta Ads',
    location: 'Patna, Bihar',
    badge: 'Patna #1 Sweet Brand',
    impact: '50,000+ Festive Gift Box Orders',
    img: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=700&q=80',
    tags: ['Festive Mithai', 'Local SEO #1', 'Store Footfall'],
    featured: true,
  },
  {
    id: 'food-8',
    name: 'Pizza Hut India',
    category: 'food',
    categoryName: 'Pan Pizza Brand',
    role: 'Family Meal Combo Ads, Seasonal Discount Creatives & Delivery Funnels',
    location: 'National Outlets',
    badge: 'International Chain',
    impact: '3.2x Campaign ROI',
    img: 'https://images.unsplash.com/photo-1590947132387-155cc02f3212?w=700&q=80',
    tags: ['Combo Promotions', 'Google Ads', 'Local Stores'],
  },
  {
    id: 'food-9',
    name: 'Wakhra Swaad',
    category: 'food',
    categoryName: 'Authentic Punjabi Gourmet',
    role: 'Cloud Kitchen Scaling, Swiggy/Zomato Visibility Ads & Packaging Rebranding',
    location: 'Delhi',
    badge: 'Punjabi Food Pioneer',
    impact: '2.8x Daily Delivery Orders',
    img: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=700&q=80',
    tags: ['Cloud Kitchens', 'Zomato Ads', 'Packaging Branding'],
  },
  {
    id: 'food-10',
    name: 'Ramta Continental',
    category: 'food',
    categoryName: 'Fine Dining & Banquet Landmark',
    role: 'Corporate Luncheon Ads, Wedding Banquet Lead Generation & Ambiance Video',
    location: 'Patna, Bihar',
    badge: 'Premier Continental Venue',
    impact: '150+ Banquet Inquiries/Month',
    img: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=700&q=80',
    tags: ['Banquet Leads', 'Luxury Dining', 'Corporate Events'],
  },
  {
    id: 'food-11',
    name: 'Samosa King',
    category: 'food',
    categoryName: 'Fast Casual Street Food',
    role: 'Youth Snacking Campaign, Evening Craving Push & Multi-Flavour Launch',
    location: 'Patna, Bihar',
    badge: 'Famous Street Food Outlet',
    impact: '10,000+ Daily Footfalls',
    img: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&q=80',
    tags: ['Street Food Brand', 'Viral Reels', 'Store Expansion'],
  },
  {
    id: 'food-12',
    name: 'Shanti Lal',
    category: 'food',
    categoryName: 'Heritage Pure Ghee Confectionery',
    role: 'Heritage Branding, Premium Festive Hampers & Local Search Domination',
    location: 'Patna, Bihar',
    badge: 'Generational Sweetmaker',
    impact: 'Ranked #1 on Local Sweets Search',
    img: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=700&q=80',
    tags: ['Heritage Sweets', 'Local Search', 'Festive Hampers'],
  },
  {
    id: 'food-13',
    name: 'Food Guru Cafe',
    category: 'food',
    categoryName: 'Gen-Z Cafe & Bistro',
    role: 'Aesthetic Interior Showcase, Student Hangout Discounts & Instagram Reels',
    location: 'Delhi NCR',
    badge: 'Trending Youth Cafe',
    impact: '50K+ Gen-Z Instagram Followers',
    img: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=700&q=80',
    tags: ['Cafe Aesthetics', 'Student Deals', 'Coffee Culture'],
  },
  {
    id: 'food-14',
    name: 'Udupi Cafe India',
    category: 'food',
    categoryName: 'Pure Vegetarian South Indian Chain',
    role: 'Morning Breakfast Walk-In Ads, Filter Coffee Brand Films & Health Angle',
    location: 'Delhi NCR',
    badge: 'Authentic South Indian',
    impact: '2.5x Morning Walk-In Sales',
    img: 'https://images.unsplash.com/photo-1630383249896-424e482df921?w=700&q=80',
    tags: ['Pure Veg Dining', 'Morning Footfall', 'Filter Coffee'],
  },
  {
    id: 'food-15',
    name: 'Ashu Chole Bhature Outlet',
    category: 'food',
    categoryName: 'Iconic Street Food Chain',
    role: 'Food Blogger Collaborations, Sunday Breakfast Craving Campaigns',
    location: 'Delhi NCR',
    badge: 'Popular Street Outlet',
    impact: '5M+ Food Blogger Reel Reach',
    img: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=700&q=80',
    tags: ['Food Blogging', 'Sunday Rush', 'Local Dominance'],
  },
  {
    id: 'food-16',
    name: 'Pizza Galleria',
    category: 'food',
    categoryName: 'Artisan Crust Pizza Chain',
    role: 'BOGO Offer Campaigns, Student Town Outlets Geo-Targeting & Visual Ads',
    location: 'North India Outlets',
    badge: 'Fast Growing Chain',
    impact: '4x Coupon Redemptions',
    img: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=700&q=80',
    tags: ['Coupon Campaigns', 'Artisan Crust', 'Student Markets'],
  },
  {
    id: 'food-17',
    name: 'Afraa Restaurant & Lounge',
    category: 'food',
    categoryName: 'Premium Nightlife & Gourmet Dining',
    role: 'Live Band Weekend Ads, Cocktail Menu Shoots & High-End Guest Management',
    location: 'Metropolitan Lounge',
    badge: 'Luxury Lounge & Bar',
    impact: 'Sold-Out Weekend Tables',
    img: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=700&q=80',
    tags: ['Nightlife Media', 'Cocktail Menus', 'Live Music Events'],
  },

  // ═══════════════════════════════════════════════════════
  // 🛍️ RETAIL, MALLS, TECH & CONSUMER BRANDS (19 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'ret-1',
    name: 'Zepto',
    category: 'retail',
    categoryName: 'Quick Commerce Unicorn',
    role: 'Hyperlocal Launch Campaigns, Dark Store Neighborhood Ads & App Installs',
    location: 'Metro & Tier-1 Hubs',
    badge: '10-Min Delivery Unicorn',
    impact: '200K+ First-Time App Users',
    img: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=700&q=80',
    tags: ['Hyperlocal Installs', 'Dark Stores', 'Quick Commerce'],
    featured: true,
  },
  {
    id: 'ret-2',
    name: 'Blinkit',
    category: 'retail',
    categoryName: 'Leading Quick Commerce Platform',
    role: 'Festive Flash Delivery Campaigns, Local Grocery Surge & Geo-Targeting',
    location: 'North India',
    badge: 'Zomato Group Quick Commerce',
    impact: '3.6x Festive Order Influx',
    img: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=700&q=80',
    tags: ['Festive Surges', 'Local Inventory', 'App Conversion'],
    featured: true,
  },
  {
    id: 'ret-3',
    name: 'City Centre Mall',
    category: 'retail',
    categoryName: 'Mega Shopping Mall & Entertainment',
    role: 'End-of-Season Sale Ad Blasts, Festival Carnivals & Footfall Driving Funnels',
    location: 'Patna, Bihar',
    badge: 'Premier Shopping Destination',
    impact: '250,000+ Festive Footfalls',
    img: 'https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=700&q=80',
    tags: ['Mall Footfall', 'Festival Carnivals', 'Retailer Co-Op'],
    featured: true,
  },
  {
    id: 'ret-4',
    name: 'Lacoste Clothing',
    category: 'retail',
    categoryName: 'French Luxury Designer Fashion',
    role: 'High-Net-Worth VIP Shopping Events, Autumn/Winter Collection Launch & Meta Ads',
    location: 'City Centre Mall, Patna',
    badge: 'International Luxury Brand',
    impact: '₹1.2Cr+ Seasonal Sales Volume',
    img: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=700&q=80',
    tags: ['Luxury Apparel', 'HNI Targeting', 'Collection Launch'],
    featured: true,
  },
  {
    id: 'ret-5',
    name: 'Croma Electronics',
    category: 'retail',
    categoryName: 'Consumer Electronics Megastore',
    role: 'Diwali Electronics Mega Sale, Smart TV & Smartphone Offers, Store Visits',
    location: 'Patna & East India',
    badge: 'Tata Enterprise Electronics',
    impact: '4.8x Return on Ad Spend (ROAS)',
    img: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=700&q=80',
    tags: ['Electronics Sale', 'Google Store Visits', 'Diwali Offers'],
    featured: true,
  },
  {
    id: 'ret-6',
    name: 'Aditya Vision',
    category: 'retail',
    categoryName: 'Eastern India Largest Electronics Chain',
    role: 'Mega Exchange Melas, Television Ad Digital Extensions & Local Dominance',
    location: '100+ Showrooms, Bihar & Jharkhand',
    badge: 'BSE Listed Mega Retailer',
    impact: '15M+ Bihari Customers Reached',
    img: 'https://images.unsplash.com/photo-1593344484962-796055d4a3a4?w=700&q=80',
    tags: ['Mega Melas', 'Regional Dominance', 'Omnichannel Ads'],
    featured: true,
  },
  {
    id: 'ret-7',
    name: 'iDestiny',
    category: 'retail',
    categoryName: 'Apple Premium Reseller',
    role: 'iPhone New Series Launch Campaigns, Student Back-to-School Mac Discounts',
    location: 'Patna & East India',
    badge: 'Official Apple Premium Partner',
    impact: 'Record 1st-Day iPhone Pre-Orders',
    img: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=700&q=80',
    tags: ['Apple Launches', 'Pre-Order Funnels', 'Premium Tech'],
    featured: true,
  },
  {
    id: 'ret-8',
    name: 'FirstCry',
    category: 'retail',
    categoryName: 'Asia Largest Baby & Kids Retailer',
    role: 'Mother & Baby Carnivals, Diaper Mega-Offers & Maternity Store Footfalls',
    location: 'Patna Outlets',
    badge: 'Kids & Baby Retail Leader',
    impact: '3.9x Local Mom Network Engagements',
    img: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=700&q=80',
    tags: ['Mom Community', 'Baby Care Offers', 'Store Footfalls'],
  },
  {
    id: 'ret-9',
    name: 'Sudha Milk',
    category: 'retail',
    categoryName: 'Iconic State Dairy Giant (COMFED)',
    role: 'Pure Milk & Ghee Festive Campaigns, Ice-Cream Parlour Network Promotions',
    location: 'Statewide, Bihar & Jharkhand',
    badge: 'Household Dairy Giant',
    impact: '30M+ Dairy Drinkers Touched',
    img: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=700&q=80',
    tags: ['Household FMCG', 'Purity Narrative', 'Statewide Brand'],
    featured: true,
  },
  {
    id: 'ret-10',
    name: 'Reliance Bazar',
    category: 'retail',
    categoryName: 'Pan-India Supermarket Megastore',
    role: 'Weekly Grocery Discount Blitzes, Local Newspaper-to-Digital Campaign Sync',
    location: 'Patna & Bihar',
    badge: 'Retail Giant',
    impact: 'Consistent High Footfall Weekends',
    img: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=700&q=80',
    tags: ['Hypermarket', 'Weekly Deals', 'Local SEO'],
  },
  {
    id: 'ret-11',
    name: 'Jockey',
    category: 'retail',
    categoryName: 'Premium Innerwear & Athleisure',
    role: 'Athleisure Movement Campaigns, Official Store Footfalls & Activewear Reels',
    location: 'Patna Stores',
    badge: 'Global Athleisure Giant',
    impact: '2.6x Store Walk-Ins',
    img: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=700&q=80',
    tags: ['Athleisure', 'Store Footfalls', 'Activewear'],
  },
  {
    id: 'ret-12',
    name: 'Sree Sundari Sarees',
    category: 'retail',
    categoryName: 'Heritage Bridal & Silk Wear',
    role: 'Bridal Trousseau Campaigns, Silk Weaves Video Stories & NRI Customer Catalogues',
    location: 'Patna, Bihar',
    badge: 'Famous Bridal Silk House',
    impact: '₹80L+ Bridal Booking Inquiries',
    img: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=700&q=80',
    tags: ['Bridal Silks', 'Wedding Wear', 'Catalog Leads'],
  },
  {
    id: 'ret-13',
    name: 'Ajerto',
    category: 'retail',
    categoryName: 'Trendsetting Youth Fashion',
    role: 'College Fashion Drops, Instagram Micro-Influencers & Store Launch Party',
    location: 'Boring Road, Patna',
    badge: 'Trendy High-Street Store',
    impact: '15,000+ Gen-Z Store Visits',
    img: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=700&q=80',
    tags: ['Youth Streetwear', 'College Drops', 'Influencer Party'],
  },
  {
    id: 'ret-14',
    name: 'Gokul',
    category: 'retail',
    categoryName: 'Traditional Dairy & Confectionery',
    role: 'Morning Pure Ghee Jalebi Promotions, Wedding Catering Leads & Brand Trust',
    location: 'Patna, Bihar',
    badge: 'Trusted Confectioner',
    impact: '3x Morning Breakfast Sales',
    img: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=700&q=80',
    tags: ['Pure Dairy', 'Heritage Sweets', 'Catering Orders'],
  },
  {
    id: 'ret-15',
    name: 'Shekhar Shukar Market',
    category: 'retail',
    categoryName: 'Wholesale & Retail Trading Hub',
    role: 'Wholesale B2B Buyer Campaigns, Retail Merchant Onboarding & Visibility',
    location: 'Patna, Bihar',
    badge: 'Major Commercial Hub',
    impact: '500+ Merchant Enrollments',
    img: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=700&q=80',
    tags: ['B2B Wholesale', 'Commercial Hub', 'Merchant Growth'],
  },
  {
    id: 'ret-16',
    name: 'Zypp EV',
    category: 'retail',
    categoryName: 'EV Logistics & Mobility Tech',
    role: 'Delivery Rider Recruitment Drives, B2B Fleet Partnership Lead Generation',
    location: 'Delhi NCR',
    badge: 'EV-as-a-Service Pioneer',
    impact: '10,000+ Rider Onboardings',
    img: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=700&q=80',
    tags: ['Green EV Fleet', 'Rider Recruitment', 'B2B Ads'],
  },
  {
    id: 'ret-17',
    name: 'Nagori Chai',
    category: 'retail',
    categoryName: 'Famous Street Chai Chain',
    role: 'Mumbai Cutting Chai Brand Aesthetic, Franchise Expansion Lead Funnel',
    location: 'Mumbai & Maharashtra',
    badge: 'Mumbai Tea Sensation',
    impact: '150+ Franchise Inquiries',
    img: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=700&q=80',
    tags: ['Chai Brand', 'Franchise Leads', 'Street Culture'],
  },
  {
    id: 'ret-18',
    name: 'UP Sarpanch Ji Chai',
    category: 'retail',
    categoryName: 'Desi Kulhad Chai Phenomenon',
    role: 'Kulhad Chai Viral Video Series, Highway Kiosk Franchising & Brand Films',
    location: 'Jaipur, Rajasthan',
    badge: 'Cult Chai Experience',
    impact: '8M+ Chai Lover Views',
    img: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=700&q=80',
    tags: ['Kulhad Chai', 'Franchise Funnels', 'Viral Video'],
  },
  {
    id: 'ret-19',
    name: 'Fyep_in',
    category: 'retail',
    categoryName: 'D2C Streetwear & Apparel',
    role: 'Full D2C E-Commerce Setup, Meta ROAS Optimization & Apparel Lookbooks',
    location: 'Pan-India',
    badge: 'Trendy D2C Apparel',
    impact: '4.2x Meta Ad ROAS',
    img: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?w=700&q=80',
    tags: ['D2C Fashion', 'E-Commerce ROAS', 'Instagram Shop'],
  },

  // ═══════════════════════════════════════════════════════
  // 🏨 HOTELS, LUXURY RESORTS & HOSPITALITY (10 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'hosp-1',
    name: 'La Cabana Beach Resort',
    category: 'hospitality',
    categoryName: '5-Star Luxury Beach Resort',
    role: 'Destination Wedding Leads, Sunset Cabana Booking Ads & Influencer Stays',
    location: 'Ashwem Beach, Goa',
    badge: 'Goa Premier Luxury Resort',
    impact: '92% Peak Season Occupancy',
    img: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=700&q=80',
    tags: ['Goa Destination Weddings', 'Luxury Stays', 'Meta Ads'],
    featured: true,
  },
  {
    id: 'hosp-2',
    name: 'The Neeraj Riveria Resort',
    category: 'hospitality',
    categoryName: 'Riverside Luxury Wellness Retreat',
    role: 'Ganga Riverside Retreat Campaigns, Ayurvedic Spa & Yoga Retreat Bookings',
    location: 'Rishikesh, Uttarakhand',
    badge: 'Himalayan Luxury Wellness',
    impact: '300+ High-Ticket Booking Inquiries',
    img: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=80',
    tags: ['Wellness Retreats', 'Luxury Tourism', 'Google Ads'],
    featured: true,
  },
  {
    id: 'hosp-3',
    name: 'The Taj Studio',
    category: 'hospitality',
    categoryName: 'Luxury Hospitality & Creative Suites',
    role: 'Executive Stay Campaigns, High-End Shoots & Celebrity Hosting Promotion',
    location: 'Noida, Delhi NCR',
    badge: 'Elite Luxury Suites',
    impact: '3.8x Corporate Booking Surge',
    img: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=700&q=80',
    tags: ['Luxury Suites', 'Corporate Stays', 'Celebrity Shoots'],
    featured: true,
  },
  {
    id: 'hosp-4',
    name: 'Carlton Hotel',
    category: 'hospitality',
    categoryName: 'International 5-Star Hotel',
    role: 'Indian Tourist Seasonal Packages, Luxury Rooftop Dining & Suite Campaigns',
    location: 'Bangkok, Thailand',
    badge: 'International 5-Star',
    impact: '4.1x Indian Tourist Bookings',
    img: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=700&q=80',
    tags: ['International Luxury', 'Bangkok Travel', 'Skyline Suites'],
    featured: true,
  },
  {
    id: 'hosp-5',
    name: 'Hotel Mayur',
    category: 'hospitality',
    categoryName: 'Heritage Business Hotel',
    role: 'Corporate Conference Leads, Government Delegations Stays & Banquet Ads',
    location: 'Lucknow, Uttar Pradesh',
    badge: 'City Center Landmark',
    impact: '80% Consistent Weekday Occupancy',
    img: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=700&q=80',
    tags: ['Business Travel', 'Banquet Inquiries', 'Local SEO'],
  },
  {
    id: 'hosp-6',
    name: 'Sunshine Resort',
    category: 'hospitality',
    categoryName: 'Royal Palace & Resort',
    role: 'Royal Rajasthani Wedding Packages, Desert Cultural Evenings Promotion',
    location: 'Jaipur, Rajasthan',
    badge: 'Royal Heritage Resort',
    impact: '40+ Royal Wedding Bookings',
    img: 'https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=700&q=80',
    tags: ['Royal Weddings', 'Rajasthan Tourism', 'Heritage Stay'],
  },
  {
    id: 'hosp-7',
    name: 'Vedanta Heritage Hotel',
    category: 'hospitality',
    categoryName: 'Spiritual Boutique Stay',
    role: 'Pilgrimage VIP Suites, Temple Darshan Stays & Devotional Travel Funnels',
    location: 'Vrindavan, Uttar Pradesh',
    badge: 'Spiritual Haven',
    impact: '100% Sold Out on Janmashtami & Holi',
    img: 'https://images.unsplash.com/photo-1549294413-26f195200c16?w=700&q=80',
    tags: ['Pilgrimage Stays', 'Spiritual Tourism', 'VIP Suites'],
  },
  {
    id: 'hosp-8',
    name: 'The Pause',
    category: 'hospitality',
    categoryName: 'Boutique Holy City Retreat',
    role: 'Mahakal Darshan Luxury Stay Campaigns, Mindful Hospitality & Weekend Escapes',
    location: 'Ujjain, Madhya Pradesh',
    badge: 'Boutique Holy Retreat',
    impact: '4.5x Direct Website Bookings',
    img: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=700&q=80',
    tags: ['Ujjain Tourism', 'Direct Bookings', 'Boutique Stays'],
  },
  {
    id: 'hosp-9',
    name: 'The Surya Hotel',
    category: 'hospitality',
    categoryName: 'Business & Event Landmark',
    role: 'Exhibition & Convention Space Promotion, Fine Dine Multi-Cuisine Footfalls',
    location: 'North India',
    badge: 'Business Hospitality',
    impact: '120+ Corporate Events Hosted',
    img: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=700&q=80',
    tags: ['Conventions', 'Corporate Stays', 'Exhibitions'],
  },
  {
    id: 'hosp-10',
    name: 'Morning Kiss',
    category: 'hospitality',
    categoryName: 'International Boutique Stay & Cafe',
    role: 'Expat & Backpacker Social Campaigns, Tropical Cafe Branding & Reels',
    location: 'Bangkok, Thailand',
    badge: 'Tropical Lifestyle Brand',
    impact: '25K+ International Tourist Walk-Ins',
    img: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=700&q=80',
    tags: ['Backpacker Travel', 'Bangkok Lifestyle', 'Cafe Branding'],
  },

  // ═══════════════════════════════════════════════════════
  // ✈️ AVIATION, MOBILITY, TRAVEL & INFRA (11 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'av-1',
    name: 'Akasa Air',
    category: 'aviation',
    categoryName: 'Commercial Airline',
    role: 'New Route Launch Campaigns, Flash Sale Ticket Ads & Passenger Acquisition',
    location: 'Pan-India',
    badge: "India's Modern Airline",
    impact: 'High-Converting Flash Seat Sales',
    img: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=700&q=80',
    tags: ['Route Launches', 'Flight Flash Sales', 'Passenger Ads'],
    featured: true,
  },
  {
    id: 'av-2',
    name: 'MakeMyTrip',
    category: 'aviation',
    categoryName: 'Leading Online Travel Platform',
    role: 'Regional Holiday Packages Promotion, Pilgrimage Circuits & Hotel Offers',
    location: 'Pan-India',
    badge: '#1 Travel Platform',
    impact: 'Multi-City High Conversion Spends',
    img: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=700&q=80',
    tags: ['Holiday Packages', 'Pilgrimage Tours', 'Hotel Bundles'],
    featured: true,
  },
  {
    id: 'av-3',
    name: 'Air Affair Aviation',
    category: 'aviation',
    categoryName: 'Private Jet Charters & Air Ambulance',
    role: 'HNI Jet Charter Funnels, Political Election Flying Leases & Emergency Medical Flights',
    location: 'National & Global',
    badge: 'Elite Private Jet Aviation',
    impact: '50+ High-Ticket Jet Charters Booked',
    img: 'https://images.unsplash.com/photo-1519074069444-1ba4ea16e6f0?w=700&q=80',
    tags: ['Private Jets', 'Election Charters', 'HNI Lead Funnels'],
    featured: true,
  },
  {
    id: 'av-4',
    name: 'Blackwood Travels',
    category: 'aviation',
    categoryName: 'European Luxury Travel Specialist',
    role: 'Switzerland & Schengen Tour Packages, NRI Vacation Ads & Visa Inquiries',
    location: 'Europe & India',
    badge: 'European Travel Operator',
    impact: '1,200+ European Tours Booked',
    img: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=700&q=80',
    tags: ['Europe Tours', 'Schengen Holidays', 'High-Ticket Travel'],
  },
  {
    id: 'av-5',
    name: 'Blackwood Overseas',
    category: 'aviation',
    categoryName: 'Global Study & Immigration Consultancy',
    role: 'Study in UK/Europe Leads, IELTS Batch Admissions & Student Visa Seminars',
    location: 'Europe & India',
    badge: 'Global Overseas Education',
    impact: '4,000+ Student Visa Inquiries',
    img: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&q=80',
    tags: ['Study Abroad', 'Student Visas', 'Higher Education Leads'],
  },
  {
    id: 'av-6',
    name: 'Ticket Dost',
    category: 'aviation',
    categoryName: 'B2B & B2C Flight Ticket Portal',
    role: 'Lowest Fare Guarantee Ads, Agent Network Onboarding & Tatkal Booking Funnels',
    location: 'Patna & Bihar',
    badge: 'Regional Ticketing Champion',
    impact: '40,000+ Flight Tickets Booked',
    img: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=700&q=80',
    tags: ['Flight Tickets', 'Lowest Fares', 'Agent Networks'],
  },
  {
    id: 'av-7',
    name: 'Roadways Cab',
    category: 'aviation',
    categoryName: 'Intercity Taxi & Logistics Fleet',
    role: 'One-Way Outstation Taxi Ads, Airport Transfer Bookings & Google Search Dominance',
    location: 'Delhi, UP & Bihar',
    badge: 'Intercity Cab Platform',
    impact: '25,000+ Rides Dispatched',
    img: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=700&q=80',
    tags: ['Outstation Cabs', 'Airport Taxis', 'Google Ads'],
  },
  {
    id: 'av-8',
    name: 'Kashyap Tour and Travels',
    category: 'aviation',
    categoryName: 'Corporate & Leisure Transport',
    role: 'Luxury Bus Fleet Rentals, Corporate Transit Contracts & Family Pilgrimage Tours',
    location: 'Patna, Bihar',
    badge: 'Reliable Travel Fleet',
    impact: '200+ Corporate Mobility Contracts',
    img: 'https://images.unsplash.com/photo-1570125909232-eb263c188f7e?w=700&q=80',
    tags: ['Luxury Buses', 'Corporate Transit', 'Fleet Booking'],
  },
  {
    id: 'av-9',
    name: 'Eklavya Construction',
    category: 'aviation',
    categoryName: 'Infrastructure & Civil Engineering',
    role: 'Government Tender Portfolios, Heavy Infra Showcases & Corporate Brand Profile',
    location: 'Ranchi, Jharkhand',
    badge: 'Major Civil Contractor',
    impact: '₹100Cr+ Project Showcases Built',
    img: 'https://images.unsplash.com/photo-1541888946425-d0fbb1861564?w=700&q=80',
    tags: ['Infrastructure', 'B2B Corporate', 'Civil Projects'],
  },
  {
    id: 'av-10',
    name: 'Sapna Hero Motors',
    category: 'aviation',
    categoryName: 'Authorized Hero MotoCorp Dealership',
    role: 'Festive Bike Dhanteras Offers, EMI Calculator Lead Ads & Test Ride Drives',
    location: 'Samastipur, Bihar',
    badge: 'Mega Two-Wheeler Dealership',
    impact: '1,500+ Two-Wheelers Sold in Festive Month',
    img: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=700&q=80',
    tags: ['Automobile Sales', 'Hero MotoCorp', 'EMI Lead Generation'],
  },
  {
    id: 'av-11',
    name: 'Sapna Bharat Gas Agency',
    category: 'aviation',
    categoryName: 'Essential Energy & LPG Network',
    role: 'Commercial Cylinder B2B Contracts, Digital Booking Help & Community Awareness',
    location: 'Samastipur, Bihar',
    badge: 'Essential Energy Distributor',
    impact: '20,000+ Active Consumer Base',
    img: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=700&q=80',
    tags: ['Energy Distribution', 'Commercial LPG', 'Local Utility'],
  },

  // ═══════════════════════════════════════════════════════
  // 🎓 EDUCATION, INSTITUTES & SPIRITUAL (11 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'edu-1',
    name: 'GD Goenka Public School',
    category: 'education',
    categoryName: 'Premier CBSE World School',
    role: 'New Academic Session Admissions, Campus Virtual Tour & Sports Infrastructure PR',
    location: 'Patna, Bihar',
    badge: 'Premier World School',
    impact: '800+ Admission Applications',
    img: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=700&q=80',
    tags: ['School Admissions', 'Campus Video', 'Parent Ads'],
    featured: true,
  },
  {
    id: 'edu-2',
    name: 'Mentors Eduserv',
    category: 'education',
    categoryName: 'IIT-JEE & NEET Premier Coaching',
    role: 'Scholarship Exam (MEST) Campaigns, Topper Testimonial Documentaries & Enrollments',
    location: 'Patna & East India',
    badge: 'Top IIT-JEE Institute',
    impact: '25,000+ Scholarship Registrations',
    img: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=700&q=80',
    tags: ['IIT-JEE Prep', 'Scholarship Funnels', 'Topper Stories'],
    featured: true,
  },
  {
    id: 'edu-3',
    name: 'Goal Coaching',
    category: 'education',
    categoryName: 'Medical & Engineering Entrance Pioneer',
    role: 'NEET Ranker Campaigns, All-India Test Series Ads & Classroom Drive',
    location: 'Patna & Pan-India',
    badge: 'NEET Medical Pioneer',
    impact: '50,000+ Medical Aspirants Reached',
    img: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=700&q=80',
    tags: ['Medical Coaching', 'NEET Ranks', 'Admission Campaigns'],
    featured: true,
  },
  {
    id: 'edu-4',
    name: 'Open Mind Birla School',
    category: 'education',
    categoryName: 'Progressive K-12 School',
    role: 'Experiential Learning Narrative, STEM Lab Showcases & Nursery Admissions',
    location: 'Patna, Bihar',
    badge: 'Birla Edutech School',
    impact: '3.2x Parent Campus Visits',
    img: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=700&q=80',
    tags: ['STEM Education', 'Nursery Admissions', 'School Branding'],
  },
  {
    id: 'edu-5',
    name: 'Mamun University',
    category: 'education',
    categoryName: 'International Higher Education',
    role: 'Indian Student Medical/Tech Admissions, Campus Accreditation PR & Global Seminars',
    location: 'Uzbekistan',
    badge: 'International University',
    impact: '500+ Indian Student Enrollments',
    img: 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=700&q=80',
    tags: ['Global Admissions', 'MBBS Abroad', 'International PR'],
    featured: true,
  },
  {
    id: 'edu-6',
    name: 'DPS Global Kids',
    category: 'education',
    categoryName: 'Pre-Primary Education Network',
    role: 'Early Learning Fun Curriculum Showcases, Toddler Daycare Enrollments',
    location: 'Patna, Bihar',
    badge: 'Pre-School Network',
    impact: '100% Playgroup Seat Fill Rate',
    img: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=700&q=80',
    tags: ['Pre-School', 'Early Education', 'Daycare Leads'],
  },
  {
    id: 'edu-7',
    name: 'Little Millennium School',
    category: 'education',
    categoryName: 'National Preschool Chain',
    role: 'Preschool Sensory Play Campaigns, Parenting Webinars & Gola Road Admissions',
    location: 'Gola Road, Patna',
    badge: 'National Preschool',
    impact: '2.5x New Parent Walk-Ins',
    img: 'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=700&q=80',
    tags: ['Preschool Chain', 'Parenting Seminars', 'Admissions'],
  },
  {
    id: 'edu-8',
    name: 'Jesus Christ High School',
    category: 'education',
    categoryName: 'Reputed ICSE/CBSE Institution',
    role: 'Academic Discipline Narrative, Alumni Achievement Spotlights & Annual Day Live',
    location: 'Gola Road, Patna',
    badge: 'Respected Heritage School',
    impact: '400+ New Enrollment Inquiries',
    img: 'https://images.unsplash.com/photo-1564981797816-1043664bf78d?w=700&q=80',
    tags: ['Heritage School', 'Academic Excellence', 'Enrollments'],
  },
  {
    id: 'edu-9',
    name: 'Impact College',
    category: 'education',
    categoryName: 'Degree & Professional Studies',
    role: 'BBA/BCA Job Placement Records, Campus Recruitment Drives & Direct Enrollments',
    location: 'Patna, Bihar',
    badge: 'Professional Degree College',
    impact: '1,200+ Degree Course Inquiries',
    img: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&q=80',
    tags: ['Degree Courses', 'Campus Placements', 'College Admissions'],
  },
  {
    id: 'edu-10',
    name: 'ISM Patna',
    category: 'education',
    categoryName: 'Management & Technology Institute',
    role: 'MBA/PGDM Admissions, Industry Corporate Guest Lectures & Placement Documentaries',
    location: 'Patna, Bihar',
    badge: 'Premier Business School',
    impact: '850+ Management Aspirants',
    img: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=700&q=80',
    tags: ['Business School', 'MBA Admissions', 'Placement Showcases'],
  },
  {
    id: 'edu-11',
    name: 'ISKCON Patna',
    category: 'education',
    categoryName: 'Spiritual, Cultural & Educational Center',
    role: 'Sri Krishna Janmashtami Mega Event Feeds, Gita Youth Classes & Prasadam Drives',
    location: 'Patna, Bihar',
    badge: 'Sri Radha Banke Bihari Mandir',
    impact: '500,000+ Janmashtami Devotees Served',
    img: 'https://images.unsplash.com/photo-1545232979-fbf68fe9b1af?w=700&q=80',
    tags: ['Spiritual Culture', 'Mega Events', 'Youth Education'],
    featured: true,
  },

  // ═══════════════════════════════════════════════════════
  // 💇 SALONS, WELLNESS & LUXURY GROOMING (4 items)
  // ═══════════════════════════════════════════════════════
  {
    id: 'sal-1',
    name: 'Looks Salon',
    category: 'salon',
    categoryName: 'National Luxury Salon Chain',
    role: 'Bridal Makeover Packages, Hair Botox Transformation Reels & High-Street Footfalls',
    location: 'Patna, Bihar',
    badge: 'Luxury Salon Chain',
    impact: '3.6x Bridal Appointment Bookings',
    img: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=700&q=80',
    tags: ['Bridal Makeovers', 'Hair Botox Reels', 'Luxury Grooming'],
    featured: true,
  },
  {
    id: 'sal-2',
    name: 'Geetanjali Salon',
    category: 'salon',
    categoryName: 'Premium High-End Hair & Beauty',
    role: 'Influencer Styling Days, Keratin Treatments & Kérastase Rituals Push',
    location: 'Patna, Bihar',
    badge: 'Award-Winning Salon',
    impact: '150+ Premium Hair Rituals/Month',
    img: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=700&q=80',
    tags: ['Hair Transformations', 'Influencer Days', 'Luxury Treatments'],
    featured: true,
  },
  {
    id: 'sal-3',
    name: 'B-Luxury Salon',
    category: 'salon',
    categoryName: 'Executive Grooming Lounge',
    role: 'Gentlemen Executive Grooming, Royal Shaves & High-End Men Makeovers',
    location: 'Lucknow, Uttar Pradesh',
    badge: 'Nawabi Luxury Grooming',
    impact: '90% Repeat Customer Retention',
    img: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=700&q=80',
    tags: ['Men Grooming', 'Executive Styling', 'Royal Treatments'],
  },
  {
    id: 'sal-4',
    name: 'Jawed Habib Salon',
    category: 'salon',
    categoryName: 'India Household Hair Care Brand',
    role: 'Affordable Hair Spa Days, Youth Styling Discounts & Local SEO Dominance',
    location: 'Patna, Bihar',
    badge: 'India Household Brand',
    impact: '5,000+ Walk-In Haircuts/Month',
    img: 'https://images.unsplash.com/photo-1562322140-8baeececf3df?w=700&q=80',
    tags: ['Hair Makeover', 'Youth Styling', 'Google Local SEO'],
  },
]
